"use client";

import { useEffect, useMemo, useRef, useState } from "react";

import {
  configuredNetwork,
  connectWallet,
  prepareStorage,
  retrieveAndVerify,
  subscribeWalletChanges,
  uploadPayload,
} from "./lib/foc/adapter";
import type {
  FocReceipt,
  FocSession,
  PrepareReceipt,
  VerificationReceipt,
} from "./lib/foc/types";
import {
  describeError,
  MIN_UPLOAD_BYTES,
  safeHttpUrl,
  toPayloadBytes,
} from "./lib/foc/verify";

const INITIAL_PAYLOAD =
  "Filecoin Onchain Cloud stores this application payload across independent providers. " +
  "The returned PieceCID identifies these exact bytes, while retrieval proves the starter works end to end. " +
  "Generated by create-foc-app.";

type Action = "connect" | "prepare" | "upload" | "verify";

function shortAddress(address: string): string {
  return `${address.slice(0, 8)}…${address.slice(-6)}`;
}

function RetrievalLink({ url }: { url: string }) {
  const safeUrl = safeHttpUrl(url);
  return safeUrl ? (
    <a href={safeUrl} target="_blank" rel="noreferrer">Retrieval URL ↗</a>
  ) : (
    <small>Provider did not return a safe HTTP retrieval URL.</small>
  );
}

export default function App() {
  const [session, setSession] = useState<FocSession | null>(null);
  const [payload, setPayload] = useState(INITIAL_PAYLOAD);
  const [preparation, setPreparation] = useState<PrepareReceipt | null>(null);
  const [receipt, setReceipt] = useState<FocReceipt | null>(null);
  const [verification, setVerification] = useState<VerificationReceipt | null>(null);
  const [active, setActive] = useState<Action | null>(null);
  const [message, setMessage] = useState("Ready. Connect a wallet to begin.");
  const originalBytes = useRef<Uint8Array | null>(null);
  const walletRevision = useRef(0);

  const bytes = useMemo(() => toPayloadBytes(payload), [payload]);
  const network = configuredNetwork();
  const validSize = bytes.byteLength >= MIN_UPLOAD_BYTES;
  const isPrepared = preparation?.dataSize === bytes.byteLength;

  useEffect(() => subscribeWalletChanges(() => {
    walletRevision.current += 1;
    setSession(null);
    setPreparation(null);
    setReceipt(null);
    setVerification(null);
    originalBytes.current = null;
    setMessage("Wallet account or network changed. Reconnect to continue safely.");
  }), []);

  async function run(action: Action, operation: () => Promise<void>) {
    setActive(action);
    try {
      await operation();
    } catch (error) {
      setMessage(describeError(error));
    } finally {
      setActive(null);
    }
  }

  function requireSession(): FocSession {
    if (!session) {
      throw new Error("Connect a wallet before using Filecoin Onchain Cloud.");
    }
    return session;
  }

  function assertWalletUnchanged(revision: number) {
    if (walletRevision.current !== revision) {
      throw new Error("Wallet account or network changed during the operation. Reconnect and try again.");
    }
  }

  return (
    <main>
      <header className="hero">
        <div className="eyebrow"><span /> FILECOIN ONCHAIN CLOUD STARTER</div>
        <h1>Ship verifiable storage,<br />not storage plumbing.</h1>
        <p className="lede">
          This project was generated by <code>create-foc-app</code>. Connect, prepare,
          store two copies, and prove retrieval from one focused workflow.
        </p>
        <div className="heroMeta">
          <span className="networkDot" /> {network}
          <span className="divider" /> Synapse SDK 1.1.0
          <span className="divider" /> 2 provider copies
        </div>
      </header>

      <section className="workflow" aria-label="Filecoin setup workflow">
        <article className="stepCard">
          <div className="stepNumber">01</div>
          <div className="stepBody">
            <p className="kicker">Setup</p>
            <h2>Connect your wallet</h2>
            <p>Transactions stay in your injected wallet. No private key enters this client.</p>
            <p className="networkHint">
              {network === "calibration"
                ? "Calibration requires tFIL for gas and tUSDFC for storage."
                : "Mainnet uses real FIL for gas and USDFC for storage—review every transaction."}
              {" "}<a href="https://docs.filecoin.cloud/getting-started/" target="_blank" rel="noreferrer">Funding guide ↗</a>
            </p>
            <button
              onClick={() => run("connect", async () => {
                const connected = await connectWallet();
                setSession(connected);
                setPreparation(null);
                setReceipt(null);
                setVerification(null);
                originalBytes.current = null;
                setMessage(`Connected ${connected.address} on ${connected.network}.`);
              })}
              disabled={active !== null}
            >
              {active === "connect" ? "Connecting…" : session ? "Reconnect wallet" : "Connect wallet"}
            </button>
            {session && <div className="resultLine"><strong>{shortAddress(session.address)}</strong><span>connected</span></div>}
          </div>
        </article>

        <article className="stepCard">
          <div className="stepNumber">02</div>
          <div className="stepBody">
            <p className="kicker">Prepare</p>
            <h2>Fund storage safely</h2>
            <p>Synapse calculates the USDFC deposit and Filecoin Pay approval for this payload.</p>
            <label className="payloadLabel" htmlFor="payload">Demo payload · {bytes.byteLength} bytes</label>
            <textarea
              id="payload"
              value={payload}
              disabled={active !== null}
              onChange={(event) => {
                setPayload(event.target.value);
                setPreparation(null);
                setReceipt(null);
                setVerification(null);
                originalBytes.current = null;
              }}
              rows={5}
            />
            {!validSize && <p className="warning">Add {MIN_UPLOAD_BYTES - bytes.byteLength} more bytes to meet the PieceCID minimum.</p>}
            <button
              className="secondary"
              onClick={() => run("prepare", async () => {
                if (!validSize) throw new Error(`Payload must be at least ${MIN_UPLOAD_BYTES} bytes.`);
                const revision = walletRevision.current;
                const currentSession = requireSession();
                setPreparation(null);
                const result = await prepareStorage(currentSession, bytes.byteLength, (hash) => {
                  setMessage(`Preparation transaction submitted: ${hash}`);
                });
                assertWalletUnchanged(revision);
                setPreparation(result);
                setMessage(result.transactionHash ? "Storage funding and approval confirmed." : "Account is already ready for this upload.");
              })}
              disabled={active !== null || !validSize}
            >
              {active === "prepare" ? "Preparing…" : "Prepare storage"}
            </button>
            {preparation && (
              <div className="miniGrid">
                <span>Deposit needed<strong>{preparation.depositNeeded} USDFC units</strong></span>
                <span>Approval<strong>{preparation.includesApproval ? "included" : "not needed"}</strong></span>
              </div>
            )}
          </div>
        </article>

        <article className="stepCard featured">
          <div className="stepNumber">03</div>
          <div className="stepBody">
            <p className="kicker">Store</p>
            <h2>Create a Filecoin receipt</h2>
            <p>Store the bytes across two independent providers and normalize the onchain result.</p>
            <button
              onClick={() => run("upload", async () => {
                if (!validSize) throw new Error(`Payload must be at least ${MIN_UPLOAD_BYTES} bytes.`);
                if (!isPrepared) throw new Error("Prepare storage for the current payload before uploading.");
                const revision = walletRevision.current;
                const currentSession = requireSession();
                const snapshot = new Uint8Array(bytes);
                const result = await uploadPayload(currentSession, snapshot);
                assertWalletUnchanged(revision);
                originalBytes.current = snapshot;
                setReceipt(result);
                setVerification(null);
                setMessage(result.complete ? "Both Filecoin copies are committed." : `${result.copies.length}/${result.requestedCopies} copies committed.`);
              })}
              disabled={active !== null || !validSize || !isPrepared}
            >
              {active === "upload" ? "Storing…" : isPrepared ? "Store on Filecoin" : "Prepare before storing"}
            </button>

            {receipt && (
              <div className="receipt">
                <div className="receiptHeader"><span>PIECE RECEIPT</span><strong>{receipt.complete ? "COMPLETE" : "PARTIAL"}</strong></div>
                <code className="pieceCid">{receipt.pieceCid}</code>
                <div className="receiptMeta">
                  <span>Size<strong>{receipt.size} bytes</strong></span>
                  <span>Copies<strong>{receipt.copies.length}/{receipt.requestedCopies}</strong></span>
                </div>
                <div className="copyList">
                  {receipt.copies.map((copy) => (
                    <div key={`${copy.providerId}-${copy.dataSetId}`}>
                      <span>{copy.role}</span>
                      <strong>Provider {copy.providerId}</strong>
                      <small>Dataset {copy.dataSetId} · Piece {copy.pieceId}</small>
                      <RetrievalLink url={copy.retrievalUrl} />
                    </div>
                  ))}
                </div>
                {receipt.failedAttempts.length > 0 && (
                  <div className="failedAttempts">
                    <strong>Failed provider attempts</strong>
                    {receipt.failedAttempts.map((attempt, index) => (
                      <p key={`${attempt.providerId}-${attempt.role}-${index}`}>
                        Provider {attempt.providerId} · {attempt.role}: {attempt.error}
                      </p>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </article>

        <article className="stepCard">
          <div className="stepNumber">04</div>
          <div className="stepBody">
            <p className="kicker">Verify</p>
            <h2>Retrieve the exact bytes</h2>
            <p>Download by PieceCID and compare every byte with the uploaded snapshot.</p>
            <button
              className="secondary"
              onClick={() => run("verify", async () => {
                if (!receipt || !originalBytes.current) throw new Error("Store a payload before verifying it.");
                const revision = walletRevision.current;
                const currentSession = requireSession();
                const result = await retrieveAndVerify(currentSession, receipt.pieceCid, originalBytes.current);
                assertWalletUnchanged(revision);
                setVerification(result);
                setMessage(result.matchesOriginal ? "Retrieval verified byte for byte." : "Retrieved bytes do not match the original payload.");
              })}
              disabled={active !== null || !receipt}
            >
              {active === "verify" ? "Retrieving…" : "Retrieve & verify"}
            </button>
            {verification && (
              <div className={verification.matchesOriginal ? "verification pass" : "verification fail"}>
                <span>{verification.matchesOriginal ? "✓" : "!"}</span>
                <div><strong>{verification.matchesOriginal ? "Verified" : "Mismatch"}</strong><small>{verification.byteLength} bytes retrieved</small></div>
              </div>
            )}
          </div>
        </article>
      </section>

      <footer role="status" aria-live="polite">
        <span className="statusLabel">STATUS</span>
        <p>{message}</p>
        <a href="https://docs.filecoin.cloud/" target="_blank" rel="noreferrer">FOC documentation ↗</a>
      </footer>
    </main>
  );
}
