import type { Metadata } from "next";
import type { ReactNode } from "react";

import "./globals.css";

export const metadata: Metadata = {
  title: "__PROJECT_NAME__ · Filecoin Onchain Cloud",
  description: "A verifiable Filecoin Onchain Cloud starter generated by create-foc-app.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
